### ISSUE TITLE
Guntenberg and Widget translation

### ISSUE THREAD

**Issue by fremsoft** [clivezhg/more-lang#3]
Hello, I notice that Gutenberg editor is not allowing to display extra languages. 
With Wordpress 5 the Plugin seems to not working properly. 
I'm using Spacious Theme (https://demo.themegrill.com/spacious/) and Widgets are not translating at all.
Please give me feedback about  this issue.

Thank You

**Comment by clivezhg** [comment]
Sorry, this issue was neglected by me till now. Gutenberg is a new stuff in Wordpress, I think the issue was resolved in the recent releases. Could you use the latest release and verify? Thanks!
