### ISSUE TITLE
Can't save changes in settings

### ISSUE THREAD

**Issue by Kaorinite** [clivezhg/more-lang#4]
Hi!

I've installed your plugin and wanted to add two locales, however, when I clicked the "Save changes" button, nothing was saved. :( I'm using Wordpress 5.1.1. 
Could you tell me, please, what could be the problem here?

**Comment by clivezhg** [comment]
Sorry, this issue was neglected by me till now. I think this issue was resolved in the Release 1.8.7, could you use the latest release and verify? Thanks!

**Comment by clivezhg** [comment]
Resolved
